name: Test & Publish to TestPyPI
on:
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build-n-publish:
        name: Build and publish Python distributions to PyPI
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@master
            - name: Set up python 3.9
              uses: actions/setup-python@v3
              with:
                  python-version: "3.9"

            # Installs and upgrades pip and the build dependencies
            - name: "Installs and upgrades pip and build dependencies"
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install build twine
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            # Tests with unittest
            - name: Test with unittest
              run: |
                  cd tests
                  python3 -m unittest discover
                  cd ..

            # Upload to TestPyPI
            - name: Build and Upload to TestPyPI
              run: |
                  rm -rf dist build *.egg-info *.egg
                  python3 -m build
                  python3 -m twine upload --skip-existing dist/*
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_TOKEN }}
                  TWINE_REPOSITORY: testpypi
